### ISSUE TITLE
Ability to delete ECR repositories from DataSourceAnalysisNestedStack

### ISSUE THREAD

**Issue by luisgrac** [aws-samples/automated-language-analysis#1]
Upon `$ cdk destroy`, LanguageAnalysis-DataSourceAnalysisNestedStack results in `DELETE_FAILED` due to event:

> The following resource(s) failed to delete: [ErrorsPipelineECRRepositoryXXXXXXXX, MetricsPipelineECRRepositoryYYYYYYYY].

Because they're resources created outside of CDK and therefore CDK does not have permission or capabilities to delete those.

Please consider using a [AWS Lambda-backed custom resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources-lambda.html) to delete all un-deleted resources from main Stack, as a hotfix.

**Comment by bpguasch** [comment]
Thank you,

This is an interesting feature. Will work on it.

**Comment by bpguasch** [comment]
Feature implemented.
